const actionTypes = {
    CURRENT_ITEM: "CURRENT_ITEM_ACTION",
    CART_ADD_ITEM: "CART_ADD_ITEM_ACTION",
    CART_REMOVE_ITEM: "CART_REMOVE_ITEM_ACTION",
    CART_SUBTRACT_ITEM: "CART_SUBTRACT_ITEM_ACTION",
    CART_EMPTY: "CART_EMPTY_ACTION",
};

export default actionTypes;
